CAPITAL_MAP = {
    "Aceh": "Banda Aceh",
    "Sumatera Utara": "Medan",
    "Sumatera Barat": "Padang",
    "Riau": "Pekanbaru",
    "Jambi": "Jambi",
    "Sumatera Selatan": "Palembang",
    "Bengkulu": "Bengkulu",
    "Lampung": "Bandar Lampung",
    "Kepulauan Bangka Belitung": "Pangkal Pinang",
    "Kepulauan Riau": "Tanjung Pinang",
    "DKI Jakarta": "Jakarta",
    "Jawa Barat": "Bandung",
    "Jawa Tengah": "Semarang",
    "DI Yogyakarta": "Yogyakarta",
    "Jawa Timur": "Surabaya",
    "Banten": "Serang",
    "Bali": "Denpasar",
    "Nusa Tenggara Barat": "Mataram",
    "Nusa Tenggara Timur": "Kupang",
    "Kalimantan Barat": "Pontianak",
    "Kalimantan Tengah": "Palangka Raya",
    "Kalimantan Selatan": "Banjarbaru",
    "Kalimantan Timur": "Samarinda",
    "Kalimantan Utara": "Tanjung Selor",
    "Sulawesi Utara": "Manado",
    "Sulawesi Tengah": "Palu",
    "Sulawesi Selatan": "Makassar",
    "Sulawesi Tenggara": "Kendari",
    "Gorontalo": "Gorontalo",
    "Sulawesi Barat": "Mamuju",
    "Maluku": "Ambon",
    "Maluku Utara": "Sofifi",
    "Papua": "Jayapura",
    "Papua Barat": "Manokwari",
    "Papua Barat Daya": "Sorong",
    "Papua Selatan": "Merauke",
    "Papua Tengah": "Nabire",
    "Papua Pegunungan": "Wamena"
}