[supabase]
user     = "postgres.psmbloxtimmoonajqjvg"
password = "DBKelompok4"
host     = "aws-1-ap-southeast-1.pooler.supabase.com"
port     = "5432"
db       = "postgres"


GEMINI_API_KEY = "AQ.Ab8RN6JwSewtDbHW6Z6n5FHjUTBXdB9sXDtJ494pwPqKXDnJXA"